// This file will be auto-generated by generate-env.js
// Do not edit manually - it will be overwritten
export const environment = {
    SUPABASE_URL: '',
    SUPABASE_SECRET_KEY: '',
    SUPABASE_ANON_KEY: '',
};
